### ISSUE TITLE
Repository Missing Files

### ISSUE THREAD

**Issue by amattas** [omnipresense/flux_capacitor#1]
This repository seems to be missing files.

**Comment by omnipresense** [comment]
I updated the readme with a link to the article (without which these resources don't make a lot of sense.)  
I don't know what missing files you are referring to otherwise.  Please reopen with suggestions!

**Comment by amattas** [comment]
flux_capacitor.ino is making reference to the class Serial, but I don't see any import for Serial and am unsure which library it actually is. On the link it looks like it may be a reference to SoftwareSerial?
